version: '3'

services:
  mysql-server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ~/docker_my/src/mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
    cap_add:
      - SYS_NICE
    

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - '10051:10051'
    restart: always
    links: 
      - mysql-server
    depends_on:
      - mysql-server

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-latest
    container_name: zabbix-web
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links: 
      - zabbix-server
    depends_on:
      - zabbix-server
